# Site settings — Unofficial Windows Documentation
# _config.yml NOT hot-reloaded. Restart w/ `jekyll serve` after edits.

title: Unofficial Windows Documentation
tagline: A reference guide for what is and isn't normal.
description: >-
  A collection of guides, references, and write-ups for Windows.
author: Bruno Christensen
email: brunojchris@gmail.com

# If deploying to <user>.github.io, baseurl: "/unofficial-windows-documentation"
# If using a custom domain, set baseurl to "" and url to domain.
baseurl: ""
url: "brunochristensen.net"

github_username: brunochristensen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
  - scope:
      path: ""
      type: pages
    values:
      layout: page

sass:
  style: compressed
  sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .jekyll-cache
